version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=passme
    ports:
      - 5432:5432
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 8282:9090
